databases:
  - name: "testdb"
    truncate:
      - name: ""
    tables:
      - name: "fee_test"
        lang: "ukr"
        # lang: "en"
        pkey_name: "fee_test_pkey"
        tmp_name: "fee_test_tmp"
        fields:
          - name: "ID"
            type: "uuid"
            tag: "`gorm:\"type: uuid; primary_key\"`"
          - name: "FirstName"
            type: "varchar"
            tag: "`gorm:\"type: varchar(255)\" sql:\"type:varchar(255)\" generated:\"type:hex\"`"
          - name: "BirthDate"
            type: "varchar"
            tag: "`gorm:\"type: date\" sql:\"type: date\"`"
          - name: "Gender"
            type: "nullString"
            tag: "`gorm:\"type: varchar(255)\" sql:\"type:varchar(255)\"`"
          - name: "TestId"
            type: "varchar"
            tag: "`gorm:\"type: varchar(255)\" sql:\"type:varchar(255)\" generated:\"type:randString\"`"
          - name: "Documents"
            type: "jsonb"
            tag: "`gorm:\"type: jsonb default '{}'::jsonb\"`"
          - name: "Phones"
            type: "jsonb"
            tag: "`gorm:\"type: jsonb default '{}'::jsonb\"`"
          - name: "InsertedBy"
            type: "uuid"
            tag: "`gorm:\"type: uuid\"`"
          - name: "InsertedAt"
            type: "timestamp"
            tag: "`gorm:\"type: time\"`"
          - name: "NoTaxId"
            type: "boolean"
            tag: "`gorm:\"type: boolen\"`"
          - name: "Specialities"
            type: "jsonb"
            tag: "`gorm:\"type: jsonb default '{}'::jsonb\"`"
          - name: "AboutMyself"
            type: "text"
            tag: "`gorm:\"type: text\"`"
          - name: "WorkingExperience"
            type: "int"
            tag: "`gorm:\"type: int\" sql:\"type:int\"`"
          - name: "SomeCustomField"
            type: "jsonb"
            tag: "`gorm:\"type: jsonb default '{}'::jsonb\" generated:\"type:customJsonb;value:{\\\"phones\\\": [{\\\"type\\\": \\\"MOBILE\\\", \\\"number\\\": \\\"123123123\\\"}], \\\"last_name\\\": \\\"lastname\\\", \\\"first_name\\\": \\\"firstname\\\", \\\"second_name\\\": \\\"secondname\\\"}\" `"
